### ISSUE TITLE
Suppor url/filepath syntax

### ISSUE THREAD

**Issue by hasufell** [hasufell/stack2cabal#26]
```yaml
- size: 285152
  subdir: wai
  url: http://github.com/yesodweb/wai/archive/2f8a8e1b771829f4a8a77c0111352ce45a14c30f.zip
  cabal-file:
    size: 1717
    sha256: 7b46e7a8b121d668351fa8a684810afadf58c39276125098485203ef274fd056

- size: 1442
  filepath: acme-missiles-0.3.tar.gz
  cabal-file:
    size: 613
    sha256: 2ba66a092a32593880a87fb00f3213762d7bca65a687d45965778deb8694c5d1
  name: acme-missiles
  version: '0.3'
  sha256: e563d8b524017a06b32768c4db8eff1f822f3fb22a90320b7e414402647b735b
  pantry-tree:
    size: 226
    sha256: 614bc0cca76937507ea0a5ccc17a504c997ce458d7f2f9e43b15a10c8eaeb033
```

**Comment by hasufell** [comment]
Another one that doesn't work:

- https://gitlab.com/pcoves/hakyll-contrib-i18n/-/raw/master/stack.yaml
- https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/20.yaml

1. resolver can be an object

```
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/20.yaml
```

2. packages can have hackage deps

```
packages:
- hackage: AC-Angle-1.0@sha256:e1ffee97819283b714598b947de323254e368f6ae7d4db1d3618fa933f80f065,544
  pantry-tree:
    size: 210
    sha256: 7edd1f1a6228af27c0f0ae53e73468c1d7ac26166f2cb386962db7ff021a2714
```
