### ISSUE TITLE
extra-deps fields from stack.yaml overwrite resolver, possibly ingoring subdirs

### ISSUE THREAD

**Issue by hasufell** [hasufell/stack2cabal#30]
Example https://github.com/input-output-hk/smash

----

resolver has:

```yaml
- git: https://github.com/input-output-hk/ouroboros-network
  commit: f0eb6e439e7c0121476ded5e88d2f638e8aa36ac
  subdirs:
  - io-sim
  - io-sim-classes
  - network-mux
  - ntp-client
  - ouroboros-network
  - ouroboros-consensus
  - ouroboros-consensus-byron
  - ouroboros-consensus-cardano
  - ouroboros-consensus-shelley
  - typed-protocols
  - typed-protocols-examples
  - ouroboros-network-framework
  - Win32-network
```

`stack.yaml` has:

```yaml
  # This is something extra we need.
  - git: https://github.com/input-output-hk/ouroboros-network
    commit: f0eb6e439e7c0121476ded5e88d2f638e8aa36ac
    subdirs:
    - cardano-client
```

`cabal.project` will only have:

```
source-repository-package
    type: git
    location: https://github.com/input-output-hk/ouroboros-network
    tag: f0eb6e439e7c0121476ded5e88d2f638e8aa36ac
    subdir: cardano-client
```
